from PyQt5 import QtCore, QtGui, QtWidgets
import math

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(689, 556)
        Dialog.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"")
        self.Numero1 = QtWidgets.QTextEdit(Dialog)
        self.Numero1.setGeometry(QtCore.QRect(30, 120, 104, 71))
        self.Numero1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Numero1.setObjectName("Numero1")
        self.Cociente = QtWidgets.QPushButton(Dialog)
        self.Cociente.setGeometry(QtCore.QRect(260, 200, 61, 41))
        self.Cociente.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.Cociente.setObjectName("Cociente")
        self.Resta = QtWidgets.QPushButton(Dialog)
        self.Resta.setGeometry(QtCore.QRect(100, 200, 61, 41))
        self.Resta.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.Resta.setObjectName("Resta")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(65, 60, 600, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Residuo = QtWidgets.QPushButton(Dialog)
        self.Residuo.setGeometry(QtCore.QRect(330, 200, 61, 41))
        self.Residuo.setStyleSheet("\n"
"background-color: rgb(255, 255, 127);")
        self.Residuo.setObjectName("Residuo")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(320, 150, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setMouseTracking(True)
        self.label_2.setTabletTracking(False)
        self.label_2.setAcceptDrops(False)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setLineWidth(1)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setIndent(5)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.Resultado = QtWidgets.QLabel(Dialog)
        self.Resultado.setGeometry(QtCore.QRect(390, 130, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.Resultado.setFont(font)
        self.Resultado.setText("")
        self.Resultado.setIndent(5)
        self.Resultado.setObjectName("Resultado")
        self.Suma = QtWidgets.QPushButton(Dialog)
        self.Suma.setGeometry(QtCore.QRect(30, 200, 61, 41))
        self.Suma.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.Suma.setObjectName("Suma")
        self.Operacion = QtWidgets.QLabel(Dialog)
        self.Operacion.setEnabled(True)
        self.Operacion.setGeometry(QtCore.QRect(150, 130, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Operacion.setFont(font)
        self.Operacion.setMouseTracking(True)
        self.Operacion.setTabletTracking(False)
        self.Operacion.setAcceptDrops(False)
        self.Operacion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Operacion.setAutoFillBackground(False)
        self.Operacion.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Operacion.setLineWidth(1)
        self.Operacion.setTextFormat(QtCore.Qt.AutoText)
        self.Operacion.setScaledContents(False)
        self.Operacion.setWordWrap(False)
        self.Operacion.setIndent(5)
        self.Operacion.setOpenExternalLinks(False)
        self.Operacion.setObjectName("label_5")
        self.Multiplicacion = QtWidgets.QPushButton(Dialog)
        self.Multiplicacion.setGeometry(QtCore.QRect(170, 200, 81, 41))
        self.Multiplicacion.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.Multiplicacion.setObjectName("Multiplicacion")
        self.Numero2 = QtWidgets.QTextEdit(Dialog)
        self.Numero2.setGeometry(QtCore.QRect(210, 120, 104, 71))
        self.Numero2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Numero2.setObjectName("Numero2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 340, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 300, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(30, 380, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(50, 420, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(30, 460, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(110, 500, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.Seno = QtWidgets.QPushButton(Dialog)
        self.Seno.setGeometry(QtCore.QRect(30, 250, 61, 41))
        self.Seno.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.Seno.setObjectName("Seno")
        self.Coseno = QtWidgets.QPushButton(Dialog)
        self.Coseno.setGeometry(QtCore.QRect(100, 250, 61, 41))
        self.Coseno.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.Coseno.setObjectName("Coseno")
        self.Tangente = QtWidgets.QPushButton(Dialog)
        self.Tangente.setGeometry(QtCore.QRect(170, 250, 81, 41))
        self.Tangente.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.Tangente.setObjectName("Tangente")
        self.Cotangente = QtWidgets.QPushButton(Dialog)
        self.Cotangente.setGeometry(QtCore.QRect(260, 250, 61, 41))
        self.Cotangente.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.Cotangente.setObjectName("Cotangente")
        self.Secante = QtWidgets.QPushButton(Dialog)
        self.Secante.setGeometry(QtCore.QRect(330, 250, 61, 41))
        self.Secante.setStyleSheet("\n"
"background-color: rgb(255, 255, 127);")
        self.Secante.setObjectName("Secante")
        self.Cosecante = QtWidgets.QPushButton(Dialog)
        self.Cosecante.setGeometry(QtCore.QRect(400, 250, 61, 41))
        self.Cosecante.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.Cosecante.setObjectName("Cosecante")
        self.Logo = QtWidgets.QLabel(Dialog)
        self.Logo.setGeometry(QtCore.QRect(320, 320, 341, 211))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("E:/Informacion/u/Electiva Robotica/Taller 2/logo-ecci.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.Suma.clicked.connect(self.suma)
        self.Resta.clicked.connect(self.resta)
        self.Multiplicacion.clicked.connect(self.multi)
        self.Residuo.clicked.connect(self.residuo)
        self.Cociente.clicked.connect(self.cociente)
        self.Seno.clicked.connect(self.seno)
        self.Coseno.clicked.connect(self.coseno)
        self.Tangente.clicked.connect(self.tangente)
        self.Cotangente.clicked.connect(self.cotangente)
        self.Secante.clicked.connect(self.secante)
        self.Cosecante.clicked.connect(self.cosecante)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Cociente.setText(_translate("Dialog", "Cociente"))
        self.Resta.setText(_translate("Dialog", "Resta"))
        self.label_4.setText(_translate("Dialog", "Ingrese 2 valores: (Funciones trigonometricas solo 1 valor)"))
        self.Residuo.setText(_translate("Dialog", "Residuo"))
        self.label_2.setText(_translate("Dialog", "="))
        self.Suma.setText(_translate("Dialog", "Suma"))
        self.Operacion.setText(_translate("Dialog", "?"))
        self.Multiplicacion.setText(_translate("Dialog", "Multiplicacion"))
        self.label.setText(_translate("Dialog", "Wendy Dayan Silva Venegas - 66934"))
        self.label_6.setText(_translate("Dialog", "Juan Esteban Sanchez Lamprea - 66912"))
        self.label_7.setText(_translate("Dialog", "Juan Camio Luna Calderon - 90522"))
        self.label_8.setText(_translate("Dialog", "Juan Bernal Garcia - 87190"))
        self.label_9.setText(_translate("Dialog", "Ing Mecatronica. Electiva de robotica"))
        self.label_10.setText(_translate("Dialog", "2024-1"))
        self.Seno.setText(_translate("Dialog", "Seno"))
        self.Coseno.setText(_translate("Dialog", "Coseno"))
        self.Tangente.setText(_translate("Dialog", "Tangente"))
        self.Cotangente.setText(_translate("Dialog", "Cotangente"))
        self.Secante.setText(_translate("Dialog", "Secante"))
        self.Cosecante.setText(_translate("Dialog", "Cosecante"))
    def suma(self):
        a = self.Numero1.toPlainText()
        b = self.Numero2.toPlainText()
        c = int(a)+int(b)
        self.Resultado.setText(str(c))
        self.Operacion.setText("+")
    def resta(self):
        a = self.Numero1.toPlainText()
        b = self.Numero2.toPlainText()
        c = int(a)-int(b)
        self.Resultado.setText(str(c))
        self.Operacion.setText("-")

    def multi(self):
        a = self.Numero1.toPlainText()
        b = self.Numero2.toPlainText()
        c = int(a)*int(b)
        self.Resultado.setText(str(c))
        self.Operacion.setText("x")
    def cociente(self):
        a = self.Numero1.toPlainText()
        b = self.Numero2.toPlainText()
        c = int(a)/int(b)
        self.Resultado.setText(str(c))
        self.Operacion.setText("/")
    def residuo(self):
        a = self.Numero1.toPlainText()
        b = self.Numero2.toPlainText()
        c = int(a)%int(b)
        self.Resultado.setText(str(c))
        self.Operacion.setText("%")
    def seno(self):
        a = float(self.Numero1.toPlainText())
        c = math.sin(math.radians(a))
        self.Resultado.setText(str(c))
        self.Operacion.setText("sin")

    def coseno(self):
        a = float(self.Numero1.toPlainText())
        c = math.cos(math.radians(a))
        self.Resultado.setText(str(c))
        self.Operacion.setText("cos")

    def tangente(self):
        a = float(self.Numero1.toPlainText())
        c = math.tan(math.radians(a))
        self.Resultado.setText(str(c))
        self.Operacion.setText("tan")

    def cotangente(self):
        a = float(self.Numero1.toPlainText())
        c = 1 / math.tan(math.radians(a))
        self.Resultado.setText(str(c))
        self.Operacion.setText("ctg")

    def secante(self):
        a = float(self.Numero1.toPlainText())
        c = 1 / math.cos(math.radians(a))
        self.Resultado.setText(str(c))
        self.Operacion.setText("sec")

    def cosecante(self):
        a = float(self.Numero1.toPlainText())
        c = 1 / math.sin(math.radians(a))
        self.Resultado.setText(str(c))
        self.Operacion.setText("csc")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
