from PyQt5 import QtCore, QtGui, QtWidgets
import RPi.GPIO as GPIO
import time

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(588, 620)
        Dialog.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 410, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(0, 370, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(90, 570, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 450, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(30, 490, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(10, 530, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.Mov_ser = QtWidgets.QSlider(Dialog)
        self.Mov_ser.setGeometry(QtCore.QRect(240, 140, 160, 22))
        self.Mov_ser.setMaximum(180)
        self.Mov_ser.setOrientation(QtCore.Qt.Horizontal)
        self.Mov_ser.setObjectName("Mov_ser")
        self.Mov_ser.valueChanged.connect(self.update_values)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 140, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setTabletTracking(False)
        self.label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label.setAcceptDrops(False)
        self.label.setAutoFillBackground(False)
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.Angulo = QtWidgets.QLabel(Dialog)
        self.Angulo.setGeometry(QtCore.QRect(240, 200, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Angulo.setFont(font)
        self.Angulo.setObjectName("Angulo")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(170, 210, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setMouseTracking(False)
        self.label_5.setTabletTracking(False)
        self.label_5.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_5.setAcceptDrops(False)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(False)
        self.label_5.setOpenExternalLinks(False)
        self.label_5.setObjectName("label_5")
        self.Servo = QtWidgets.QTextEdit(Dialog)
        self.Servo.setGeometry(QtCore.QRect(60, 130, 71, 41))
        self.Servo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Servo.setObjectName("Servo")
        self.Servo.textChanged.connect(self.update_values)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setMouseTracking(False)
        self.label_2.setTabletTracking(False)
        self.label_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_2.setAcceptDrops(False)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.Logo = QtWidgets.QLabel(Dialog)
        self.Logo.setGeometry(QtCore.QRect(290, 370, 271, 231))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("../Punto 1-A/logo-ecci.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(220, 100, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(310, 100, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(380, 100, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        GPIO.setmode(GPIO.BCM)
        GPIO.setup(19, GPIO.OUT)
        GPIO.setup(16, GPIO.OUT)

        self.servo1 = GPIO.PWM(19, 50)  # GPIO 19 para Servo 1 con frecuencia de 50Hz
        self.servo2 = GPIO.PWM(16, 50)  # GPIO 16 para Servo 2 con frecuencia de 50Hz
        self.servo1.start(0)
        self.servo2.start(0)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Wendy Dayan Silva Venegas - 66934"))
        self.label_6.setText(_translate("Dialog", "Juan Esteban Sanchez Lamprea - 66912"))
        self.label_10.setText(_translate("Dialog", "2024-1"))
        self.label_7.setText(_translate("Dialog", "Juan Camio Luna Calderon - 90522"))
        self.label_8.setText(_translate("Dialog", "Juan Bernal Garcia - 87190"))
        self.label_9.setText(_translate("Dialog", "Ing Mecatronica. Electiva de robotica"))
        self.label.setText(_translate("Dialog", "Servo "))
        self.Angulo.setText(_translate("Dialog", "Seleccionar servo"))
        self.label_5.setText(_translate("Dialog", "Angulo:"))
        self.label_2.setText(_translate("Dialog", "Servo 1 o 2 :"))
        self.label_11.setText(_translate("Dialog", "0°"))
        self.label_12.setText(_translate("Dialog", "90°"))
        self.label_13.setText(_translate("Dialog", "180°"))
    def update_values(self):
        servo_selected = self.Servo.toPlainText()
        angle = self.Mov_ser.value()

        if servo_selected == "1":
            self.servo1.ChangeDutyCycle(0)
            self.Angulo.setText(f"{angle}° (Servo 1)")
            duty = angle / 18.0 + 2.5
            self.servo1.ChangeDutyCycle(duty)
        elif servo_selected == "2":
            self.servo2.ChangeDutyCycle(0)
            self.Angulo.setText(f"{angle}° (Servo 2)")
            duty = angle / 18.0 + 2.5
            self.servo2.ChangeDutyCycle(duty)
        else:
            self.Angulo.setText("Seleccionar servo")
            self.servo2.ChangeDutyCycle(0)
            self.servo1.ChangeDutyCycle(0)
    def __del__(self):
        # Detener PWM y limpiar GPIO
        self.servo1.stop()
        self.servo2.stop()
        GPIO.cleanup() 


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())