<<<<<<< HEAD
import sys
import numpy as np
import matplotlib.pyplot as plt
from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas

class TrigFunctionsPlotter(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi()
        self.pushButton.clicked.connect(self.plot_trig_function)

    def setupUi(self):
        self.setObjectName("Dialog")
        self.resize(699, 707)
        self.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.funciones_lista = QtWidgets.QComboBox(self)
        self.funciones_lista.setGeometry(QtCore.QRect(50, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.funciones_lista.setFont(font)
        self.funciones_lista.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.funciones_lista.setObjectName("funciones_lista")
        self.funciones_lista.addItem("")
        self.funciones_lista.addItem("")
        self.funciones_lista.addItem("")
        self.funciones_lista.addItem("")
        self.funciones_lista.addItem("")
        self.funciones_lista.addItem("")
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(50, 340, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButton.setObjectName("pushButton")
        self.Grafica = QtWidgets.QLabel(self)
        self.Grafica.setGeometry(QtCore.QRect(150, 20, 461, 281))
        self.Grafica.setText("")
        self.Grafica.setScaledContents(True)
        self.Grafica.setObjectName("Grafica")
        self.minimo = QtWidgets.QTextEdit(self)
        self.minimo.setGeometry(QtCore.QRect(290, 350, 61, 31))
        self.minimo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.minimo.setObjectName("minimo")
        self.maximo = QtWidgets.QTextEdit(self)
        self.maximo.setGeometry(QtCore.QRect(490, 350, 61, 31))
        self.maximo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.maximo.setObjectName("maximo")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(210, 350, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(410, 350, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self)
        self.label_7.setGeometry(QtCore.QRect(40, 490, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self)
        self.label_8.setGeometry(QtCore.QRect(60, 530, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self)
        self.label_10.setGeometry(QtCore.QRect(120, 610, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(40, 450, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setGeometry(QtCore.QRect(30, 410, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self)
        self.label_9.setGeometry(QtCore.QRect(40, 570, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setGeometry(QtCore.QRect(370, 420, 261, 241))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("E:/Informacion/u/Electiva Robotica/Taller 2/logo-ecci.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "Dialog"))
        self.funciones_lista.setItemText(0, _translate("Dialog", "Seno"))
        self.funciones_lista.setItemText(1, _translate("Dialog", "Coseno"))
        self.funciones_lista.setItemText(2, _translate("Dialog", "Tangente"))
        self.funciones_lista.setItemText(3, _translate("Dialog", "Cotangente"))
        self.funciones_lista.setItemText(4, _translate("Dialog", "Secante"))
        self.funciones_lista.setItemText(5, _translate("Dialog", "Cosecante"))
        self.pushButton.setText(_translate("Dialog", "Graficar"))
        self.label.setText(_translate("Dialog", "Minimo :"))
        self.label_2.setText(_translate("Dialog", "Maximo :"))
        self.label_7.setText(_translate("Dialog", "Juan Camio Luna Calderon - 90522"))
        self.label_8.setText(_translate("Dialog", "Juan Bernal Garcia - 87190"))
        self.label_10.setText(_translate("Dialog", "2024-1"))
        self.label_3.setText(_translate("Dialog", "Wendy Dayan Silva Venegas - 66934"))
        self.label_6.setText(_translate("Dialog", "Juan Esteban Sanchez Lamprea - 66912"))
        self.label_9.setText(_translate("Dialog", "Ing Mecatronica. Electiva de robotica"))

    def plot_trig_function(self):
        func_index = self.funciones_lista.currentIndex()
        if func_index == 0:
            func = np.sin
        elif func_index == 1:
            func = np.cos
        elif func_index == 2:
            func = np.tan
        elif func_index == 3:
            func = lambda x: 1/np.tan(x)
        elif func_index == 4:
            func = lambda x: 1/np.cos(x)
        elif func_index == 5:
            func = lambda x: 1/np.sin(x)

        x_min = float(self.minimo.toPlainText())
        x_max = float(self.maximo.toPlainText())

        x = np.linspace(x_min, x_max, 400)
        y = func(x)

        fig, ax = plt.subplots()
        ax.plot(x, y)
        ax.set_xlabel('x')
        ax.set_ylabel('y')
        ax.set_title(f'Gráfica de {self.funciones_lista.currentText()}')
        ax.grid(True)

        # Convertir la gráfica a una imagen
        canvas = FigureCanvas(fig)
        canvas.draw()
        pixmap = canvas.grab()

        # Mostrar la imagen en el QLabel
        self.Grafica.setPixmap(pixmap)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    ui = TrigFunctionsPlotter()
    ui.show()
    sys.exit(app.exec_())
=======
# -*- coding: utf-8 -*-
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas


class TrigFunctionsPlotter(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi()
        self.pushButton.clicked.connect(self.plot_trig_function)

    def setupUi(self):
        self.setObjectName("Dialog")
        self.resize(699, 707)
        self.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.funciones_lista = QtWidgets.QComboBox(self)
        self.funciones_lista.setGeometry(QtCore.QRect(50, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.funciones_lista.setFont(font)
        self.funciones_lista.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.funciones_lista.setObjectName("funciones_lista")
        self.funciones_lista.addItem("")
        self.funciones_lista.addItem("")
        self.funciones_lista.addItem("")
        self.funciones_lista.addItem("")
        self.funciones_lista.addItem("")
        self.funciones_lista.addItem("")
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(50, 340, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButton.setObjectName("pushButton")
        self.Grafica = QtWidgets.QLabel(self)
        self.Grafica.setGeometry(QtCore.QRect(150, 20, 461, 281))
        self.Grafica.setText("")
        self.Grafica.setScaledContents(True)
        self.Grafica.setObjectName("Grafica")
        self.minimo = QtWidgets.QTextEdit(self)
        self.minimo.setGeometry(QtCore.QRect(290, 350, 61, 31))
        self.minimo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.minimo.setObjectName("minimo")
        self.maximo = QtWidgets.QTextEdit(self)
        self.maximo.setGeometry(QtCore.QRect(490, 350, 61, 31))
        self.maximo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.maximo.setObjectName("maximo")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(210, 350, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(410, 350, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self)
        self.label_7.setGeometry(QtCore.QRect(40, 490, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self)
        self.label_8.setGeometry(QtCore.QRect(60, 530, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self)
        self.label_10.setGeometry(QtCore.QRect(120, 610, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(40, 450, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setGeometry(QtCore.QRect(30, 410, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self)
        self.label_9.setGeometry(QtCore.QRect(40, 570, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setGeometry(QtCore.QRect(370, 420, 261, 241))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("/home/pi/Documents/Electiva_Robotica/Taller 2/logo-ecci.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "Dialog"))
        self.funciones_lista.setItemText(0, _translate("Dialog", "Seno"))
        self.funciones_lista.setItemText(1, _translate("Dialog", "Coseno"))
        self.funciones_lista.setItemText(2, _translate("Dialog", "Tangente"))
        self.funciones_lista.setItemText(3, _translate("Dialog", "Cotangente"))
        self.funciones_lista.setItemText(4, _translate("Dialog", "Secante"))
        self.funciones_lista.setItemText(5, _translate("Dialog", "Cosecante"))
        self.pushButton.setText(_translate("Dialog", "Graficar"))
        self.label.setText(_translate("Dialog", "Minimo :"))
        self.label_2.setText(_translate("Dialog", "Maximo :"))
        self.label_7.setText(_translate("Dialog", "Juan Camio Luna Calderon - 90522"))
        self.label_8.setText(_translate("Dialog", "Juan Bernal Garcia - 87190"))
        self.label_10.setText(_translate("Dialog", "2024-1"))
        self.label_3.setText(_translate("Dialog", "Wendy Dayan Silva Venegas - 66934"))
        self.label_6.setText(_translate("Dialog", "Juan Esteban Sanchez Lamprea - 66912"))
        self.label_9.setText(_translate("Dialog", "Ing Mecatronica. Electiva de robotica"))
    def plot_trig_function(self):
        func_index = self.funciones_lista.currentIndex()
        if func_index == 0:
            func = np.sin
        elif func_index == 1:
            func = np.cos
        elif func_index == 2:
            func = np.tan
        elif func_index == 3:
            func = lambda x: 1/np.tan(x)
        elif func_index == 4:
            func = lambda x: 1/np.cos(x)
        elif func_index == 5:
            func = lambda x: 1/np.sin(x)

        x_min = float(self.minimo.toPlainText())
        x_max = float(self.maximo.toPlainText())

        x = np.linspace(x_min, x_max, 400)
        y = func(x)

        fig, ax = plt.subplots()
        ax.plot(x, y)
        ax.set_xlabel('x')
        ax.set_ylabel('y')
        ax.set_title(f'Gráfica de {self.funciones_lista.currentText()}')
        ax.grid(True)

        # Convertir la gráfica a una imagen
        fig.canvas.draw()  # Esta línea es importante para actualizar el canvas
        img = np.frombuffer(fig.canvas.tostring_rgb(), dtype=np.uint8)
        img = img.reshape(fig.canvas.get_width_height()[::-1] + (3,))
        qImg = QImage(img, img.shape[1], img.shape[0], QImage.Format_RGB888)
        pixmap = QPixmap.fromImage(qImg)

        # Mostrar la imagen en el QLabel
        self.Grafica.setPixmap(pixmap)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    ui = TrigFunctionsPlotter()
    ui.show()
    sys.exit(app.exec_())
>>>>>>> 93bd2c0f80925fbafb79295064af358832d2eac4
